// Code generated by goctl. DO NOT EDIT.
// Source: interactive.proto

package interactive

import (
	"context"

	"douyin/rpc/interactive/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Comment                      = pb.Comment
	DouyinCommentActionRequest   = pb.DouyinCommentActionRequest
	DouyinCommentActionResponse  = pb.DouyinCommentActionResponse
	DouyinCommentListRequest     = pb.DouyinCommentListRequest
	DouyinCommentListResponse    = pb.DouyinCommentListResponse
	DouyinFavoriteActionRequest  = pb.DouyinFavoriteActionRequest
	DouyinFavoriteActionResponse = pb.DouyinFavoriteActionResponse
	DouyinFavoriteListRequest    = pb.DouyinFavoriteListRequest
	DouyinFavoriteListResponse   = pb.DouyinFavoriteListResponse
	User                         = pb.User
	Video                        = pb.Video

	Interactive interface {
		DouyinFavoriteAction(ctx context.Context, in *DouyinFavoriteActionRequest, opts ...grpc.CallOption) (*DouyinFavoriteActionResponse, error)
		DouyinFavoriteList(ctx context.Context, in *DouyinFavoriteListRequest, opts ...grpc.CallOption) (*DouyinFavoriteListResponse, error)
		DouyinCommentAction(ctx context.Context, in *DouyinCommentActionRequest, opts ...grpc.CallOption) (*DouyinCommentActionResponse, error)
		DouyinCommentList(ctx context.Context, in *DouyinCommentListRequest, opts ...grpc.CallOption) (*DouyinCommentListResponse, error)
	}

	defaultInteractive struct {
		cli zrpc.Client
	}
)

func NewInteractive(cli zrpc.Client) Interactive {
	return &defaultInteractive{
		cli: cli,
	}
}

func (m *defaultInteractive) DouyinFavoriteAction(ctx context.Context, in *DouyinFavoriteActionRequest, opts ...grpc.CallOption) (*DouyinFavoriteActionResponse, error) {
	client := pb.NewInteractiveClient(m.cli.Conn())
	return client.DouyinFavoriteAction(ctx, in, opts...)
}

func (m *defaultInteractive) DouyinFavoriteList(ctx context.Context, in *DouyinFavoriteListRequest, opts ...grpc.CallOption) (*DouyinFavoriteListResponse, error) {
	client := pb.NewInteractiveClient(m.cli.Conn())
	return client.DouyinFavoriteList(ctx, in, opts...)
}

func (m *defaultInteractive) DouyinCommentAction(ctx context.Context, in *DouyinCommentActionRequest, opts ...grpc.CallOption) (*DouyinCommentActionResponse, error) {
	client := pb.NewInteractiveClient(m.cli.Conn())
	return client.DouyinCommentAction(ctx, in, opts...)
}

func (m *defaultInteractive) DouyinCommentList(ctx context.Context, in *DouyinCommentListRequest, opts ...grpc.CallOption) (*DouyinCommentListResponse, error) {
	client := pb.NewInteractiveClient(m.cli.Conn())
	return client.DouyinCommentList(ctx, in, opts...)
}
