// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"douyin/api/core/internal/handler/douyinUser"
	"douyin/api/core/internal/handler/feed"
	"douyin/api/core/internal/handler/publish"
	"net/http"
	"douyin/api/core/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: douyinUser.DouyinUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: douyinUser.DouyinUserRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: douyinUser.DouyinUserLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/action",
				Handler: publish.DouyinPublishActionrHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: publish.DouyinPublishListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/publish"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/douyin/feed",
				Handler: feed.DouyinFeedHandler(serverCtx),
			},
		},
	)
}
