// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id               int64  `json:"id"`               // 用户id
	Name             string `json:"name"`             // 用户名称
	Follow_count     int64  `json:"follow_count"`     // 关注总数
	Follower_count   int64  `json:"follower_count"`   // 粉丝总数
	Is_follow        bool   `json:"is_follow"`        // true-已关注，false-未关注
	Avatar           string `json:"avatar"`           //用户头像
	Background_image string `json:"background_image"` //用户个人页顶部大图
	Signature        string `json:"signature"`        //个人简介
	Total_favorited  int64  `json:"total_favorited"`  //获赞数量
	Work_count       int64  `json:"work_count"`       //作品数量
	Favorite_count   int64  `json:"favorite_count"`   //点赞数量
}

type DouyinUserRegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type DouyinUserRegisterResp struct {
	Status_code int32  `json:"status_code"` // 状态码，0-成功，其他值-失败
	Status_msg  string `json:"status_msg"`  // 返回状态描述
	User_id     int64  `json:"user_id"`     // 用户id
	Token       string `json:"token"`       // 用户鉴权token
}

type DouyinUserLoginReq struct {
	Username string `json:"username"` // 登录用户名
	Password string `json:"password"` // 登录密码
}

type DouyinUserLoginResp struct {
	Status_code int32  `json:"status_code"` // 状态码，0-成功，其他值-失败
	Status_msg  string `json:"status_msg"`  // 返回状态描述
	User_id     int64  `json:"user_id"`     // 用户id
	Token       string `json:"token"`       // 用户鉴权token
}

type DouyinUserReq struct {
	User_id int64  `json:"user_id"` // 用户id
	Token   string `json:"token"`   // 用户鉴权token
}

type DouyinUserResp struct {
	Status_code int32  `json:"status_code"` // 状态码，0-成功，其他值-失败
	Status_msg  string `json:"status_msg"`  // 返回状态描述
	User User `json:"user"`
}

type Video struct {
	Id             int64  `json:"id"`             // 视频唯一标识
	Author *User `json:"author"`
	Play_url       string `json:"play_url"`       // 视频播放地址
	Cover_url      string `json:"cover_url"`      // 视频封面地址
	Favorite_count int64  `json:"favorite_count"` // 视频的点赞总数
	Comment_count  int64  `json:"comment_count"`  // 视频的评论总数
	Is_favorite    bool   `json:"is_favorite"`    // true-已点赞，false-未点赞
	Title          string `json:"title"`          // 视频标题
}

type DouyinFeedReq struct {
	Latest_time int64 `json:"latest_time"` // 可选参数，限制返回视频的最新投稿时间戳，精确到秒，不填表示当前时间
	Token       string `json:"token"`       // 可选参数，登录用户设置
}

type DouyinFeedResp struct {
	Status_code int32   `json:"status_code"` // 状态码，0-成功，其他值-失败
	Status_msg  string  `json:"status_msg"`  // 返回状态描述
	Video_list  []Video `json:"video_list"`  // 视频列表
	Next_time   int64   `json:"next_time"`   // 本次返回的视频中，发布最早的时间，作为下次请求时的latest_time
}

type DouyinPublishActionrReq struct {
	Token string `json:"token"` // 用户鉴权token
	Data  []byte `json:"data"`  // 视频数据
	Title string `json:"title"` // 视频标题
}

type DouyinPublishActionResp struct {
	Status_code int32  `json:"status_code"` // 状态码，0-成功，其他值-失败
	Status_msg  string `json:"status_msg"`  // 返回状态描述
}

type DouyinPublishListReq struct {
	User_id int64  `json:"user_id"` // 用户id
	Token   string `json:"token"`   // 用户鉴权token
}

type DouyinPublishListResp struct {
	Status_code int32   `json:"status_code"` // 状态码，0-成功，其他值-失败
	Status_msg  string  `json:"status_msg"`  // 返回状态描述
	Video_list  []Video `json:"video_list"`  // 用户发布的视频列表
}

type DouyinFavoriteActionRequest struct {
	Token       string `json:"token"`      // 用户鉴权token
	Video_id    int64  `json:"video_id"`    // 视频id
	Action_type int32  `json:"action_type"` // 1-点赞，2-取消点赞
}

type DouyinFavoriteActionResponse struct {
	Status_code int32  `json:"status_code"` // 状态码，0-成功，其他值-失败
	Status_msg  string `json:"status_msg"`  // 返回状态描述
}

type DouyinFavoriteListRequest struct {
	User_id int64  `json:"user_id"` // 用户id
	Token   string `json:"token"`  // 用户鉴权token
}

type DouyinFavoriteListResponse struct {
	Status_code string  `json:"status_code"` // 状态码，0-成功，其他值-失败
	Status_msg  string `json:"status_msg"`  // 返回状态描述
	Video_list  []Video `json:"videoList"`  // 用户点赞视频列表
}

type DouyinCommentActionRequest struct {
	Token        string `json:"token"`       // 用户鉴权token
	Video_id     int64  `json:"video_id"`     // 视频id
	Action_type  int32  `json:"action_type"`  // 1-发布评论，2-删除评论
	Comment_text string `json:"comment_text"` // 用户填写的评论内容，在action_type=1的时候使用
	Comment_id   int64  `json:"comment_id"`   // 要删除的评论id，在action_type=2的时候使用
}

type DouyinCommentActionResponse struct {
	Status_code int32  `json:"status_code"` // 状态码，0-成功，其他值-失败
	Status_msg  string `json:"status_msg"`  // 返回状态描述
}

type Comment struct {
	Id          int64  `json:"id"`         // 视频评论id
	User User `json:"user"`
	Content     string `json:"content"`    // 评论内容
	Create_date string `json:"create_date"` // 评论发布日期，格式 mm-dd
}

type DouyinCommentListRequest struct {
	Token    string `json:"token"`   // 用户鉴权token
	Video_id int64  `json:"videoId"` // 视频id
}

type DouyinCommentListResponse struct {
	Status_code int32  `json:"status_code"` // 状态码，0-成功，其他值-失败
	Status_msg  string `json:"status_msg"`  // 返回状态描述
	Comment_list []Comment `json:"comment_list"` // 评论列表
}

type DouyinRelationActionRequest struct {
	Token       string `json:"token"`      // 用户鉴权token
	To_user_id  int64  `json:"toUser_id"`   // 对方用户id
	Action_type int32  `json:"action_type"` // 1-关注，2-取消关注
}

type DouyinRelationActionResponse struct {
	Status_code int32  `json:"status_code"` // 状态码，0-成功，其他值-失败
	Status_msg  string `json:"status_msg"`  // 返回状态描述
}

type DouyinRelationFollowListRequest struct {
	User_id int64  `json:"user_id"` // 用户id
	Token   string `json:"token"`  // 用户鉴权token
}

type DouyinRelationFollowListResponse struct {
	Status_code int32  `json:"status_code"` // 状态码，0-成功，其他值-失败
	Status_msg  string `json:"status_msg"`  // 返回状态描述
	UserList []User `json:"user_list"`
}

type DouyinRelationFollowerListRequest struct {
	User_id int64  `json:"user_id"` // 用户id
	Token   string `json:"token"`  // 用户鉴权token
}

type DouyinRelationFollowerListResponse struct {
	Status_code int32  `json:"status_code"` // 状态码，0-成功，其他值-失败
	Status_msg  string `json:"status_msg"`  // 返回状态描述
	UserList []User `json:"user_list"`
}

type DouyinRelationFriendListRequest struct {
	User_id int64  `json:"user_id"` // 用户id
	Token   string `json:"token"`  // 用户鉴权token
}

type DouyinRelationFriendListResponse struct {
	Status_code int32  `json:"status_code"` // 状态码，0-成功，其他值-失败
	Status_msg  string `json:"status_msg"`  // 返回状态描述
	UserList []User `json:"user_list"`
}

type DouyinMessageChatRequest struct {
	Token        string `json:"token"`      // 用户鉴权token
	To_user_id   int64  `json:"to_user_id"`   // 对方用户id
	Pre_msg_time int64  `json:"pre_msg_time"` //上次最新消息的时间（新增字段-apk更新中）
}

type DouyinMessageChatResponse struct {
	Status_code int32  `json:"status_code"` // 状态码，0-成功，其他值-失败
	Status_msg  string `json:"status_msg"`  // 返回状态描述
	Message_list []Message `json:"message_list"` // 消息列表
}

type Message struct {
	Id           int64  `json:"id"`         // 消息id
	To_user_id   int64  `json:"to_user_id"`   // 该消息接收者的id
	From_user_id int64  `json:"from_user_id"` // 该消息发送者的id
	Content      string `json:"content"`    // 消息内容
	Create_time  int64 `json:"create_time"` // 消息创建时间
}

type DouyinMessageActionRequest struct {
	Token       string `json:"token"`      // 用户鉴权token
	To_user_id   int64  `json:"to_user_id"`   // 该消息接收者的id
	Action_type int32  `json:"action_type"` // 1-发送消息
	Content     string `json:"content"`    // 消息内容
}

type DouyinMessageActionResponse struct {
	Status_code int32  `json:"status_code"` // 状态码，0-成功，其他值-失败
	Status_msg  string `json:"status_msg"`  // 返回状态描述
}
