// Code generated by goctl. DO NOT EDIT.
// Source: social.proto

package social

import (
	"context"

	"douyin/rpc/social/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DouyinMessageActionRequest         = pb.DouyinMessageActionRequest
	DouyinMessageActionResponse        = pb.DouyinMessageActionResponse
	DouyinMessageChatRequest           = pb.DouyinMessageChatRequest
	DouyinMessageChatResponse          = pb.DouyinMessageChatResponse
	DouyinRelationActionRequest        = pb.DouyinRelationActionRequest
	DouyinRelationActionResponse       = pb.DouyinRelationActionResponse
	DouyinRelationFollowListRequest    = pb.DouyinRelationFollowListRequest
	DouyinRelationFollowListResponse   = pb.DouyinRelationFollowListResponse
	DouyinRelationFollowerListRequest  = pb.DouyinRelationFollowerListRequest
	DouyinRelationFollowerListResponse = pb.DouyinRelationFollowerListResponse
	DouyinRelationFriendListRequest    = pb.DouyinRelationFriendListRequest
	DouyinRelationFriendListResponse   = pb.DouyinRelationFriendListResponse
	Message                            = pb.Message
	User                               = pb.User

	Social interface {
		DouyinRelationAction(ctx context.Context, in *DouyinRelationActionRequest, opts ...grpc.CallOption) (*DouyinRelationActionResponse, error)
		DouyinRelationFollowList(ctx context.Context, in *DouyinRelationFollowListRequest, opts ...grpc.CallOption) (*DouyinRelationFollowListResponse, error)
		DouyinRelationFollowerList(ctx context.Context, in *DouyinRelationFollowerListRequest, opts ...grpc.CallOption) (*DouyinRelationFollowerListResponse, error)
		DouyinRelationFriendList(ctx context.Context, in *DouyinRelationFriendListRequest, opts ...grpc.CallOption) (*DouyinRelationFriendListResponse, error)
		DouyinMessageChat(ctx context.Context, in *DouyinMessageChatRequest, opts ...grpc.CallOption) (*DouyinMessageChatResponse, error)
		DouyinMessageAction(ctx context.Context, in *DouyinMessageActionRequest, opts ...grpc.CallOption) (*DouyinMessageActionResponse, error)
	}

	defaultSocial struct {
		cli zrpc.Client
	}
)

func NewSocial(cli zrpc.Client) Social {
	return &defaultSocial{
		cli: cli,
	}
}

func (m *defaultSocial) DouyinRelationAction(ctx context.Context, in *DouyinRelationActionRequest, opts ...grpc.CallOption) (*DouyinRelationActionResponse, error) {
	client := pb.NewSocialClient(m.cli.Conn())
	return client.DouyinRelationAction(ctx, in, opts...)
}

func (m *defaultSocial) DouyinRelationFollowList(ctx context.Context, in *DouyinRelationFollowListRequest, opts ...grpc.CallOption) (*DouyinRelationFollowListResponse, error) {
	client := pb.NewSocialClient(m.cli.Conn())
	return client.DouyinRelationFollowList(ctx, in, opts...)
}

func (m *defaultSocial) DouyinRelationFollowerList(ctx context.Context, in *DouyinRelationFollowerListRequest, opts ...grpc.CallOption) (*DouyinRelationFollowerListResponse, error) {
	client := pb.NewSocialClient(m.cli.Conn())
	return client.DouyinRelationFollowerList(ctx, in, opts...)
}

func (m *defaultSocial) DouyinRelationFriendList(ctx context.Context, in *DouyinRelationFriendListRequest, opts ...grpc.CallOption) (*DouyinRelationFriendListResponse, error) {
	client := pb.NewSocialClient(m.cli.Conn())
	return client.DouyinRelationFriendList(ctx, in, opts...)
}

func (m *defaultSocial) DouyinMessageChat(ctx context.Context, in *DouyinMessageChatRequest, opts ...grpc.CallOption) (*DouyinMessageChatResponse, error) {
	client := pb.NewSocialClient(m.cli.Conn())
	return client.DouyinMessageChat(ctx, in, opts...)
}

func (m *defaultSocial) DouyinMessageAction(ctx context.Context, in *DouyinMessageActionRequest, opts ...grpc.CallOption) (*DouyinMessageActionResponse, error) {
	client := pb.NewSocialClient(m.cli.Conn())
	return client.DouyinMessageAction(ctx, in, opts...)
}
