// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package core

import (
	"context"

	"douyin/rpc/core/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DouyinFeedRequest           = pb.DouyinFeedRequest
	DouyinFeedResponse          = pb.DouyinFeedResponse
	DouyinPublishActionRequest  = pb.DouyinPublishActionRequest
	DouyinPublishActionResponse = pb.DouyinPublishActionResponse
	DouyinPublishListRequest    = pb.DouyinPublishListRequest
	DouyinPublishListResponse   = pb.DouyinPublishListResponse
	DouyinUserLoginRequest      = pb.DouyinUserLoginRequest
	DouyinUserLoginResponse     = pb.DouyinUserLoginResponse
	DouyinUserRegisterRequest   = pb.DouyinUserRegisterRequest
	DouyinUserRegisterResponse  = pb.DouyinUserRegisterResponse
	DouyinUserRequest           = pb.DouyinUserRequest
	DouyinUserResponse          = pb.DouyinUserResponse
	User                        = pb.User
	Video                       = pb.Video

	Core interface {
		GetUserInfo(ctx context.Context, in *DouyinUserRequest, opts ...grpc.CallOption) (*DouyinUserResponse, error)
		DouyinUserRegister(ctx context.Context, in *DouyinUserRegisterRequest, opts ...grpc.CallOption) (*DouyinUserRegisterResponse, error)
		DouyinUserLogin(ctx context.Context, in *DouyinUserLoginRequest, opts ...grpc.CallOption) (*DouyinUserLoginResponse, error)
		DouyinFeed(ctx context.Context, in *DouyinFeedRequest, opts ...grpc.CallOption) (*DouyinFeedResponse, error)
		DouyinPublishAction(ctx context.Context, in *DouyinPublishActionRequest, opts ...grpc.CallOption) (*DouyinPublishActionResponse, error)
		DouyinPublishList(ctx context.Context, in *DouyinPublishListRequest, opts ...grpc.CallOption) (*DouyinPublishListResponse, error)
	}

	defaultCore struct {
		cli zrpc.Client
	}
)

func NewCore(cli zrpc.Client) Core {
	return &defaultCore{
		cli: cli,
	}
}

func (m *defaultCore) GetUserInfo(ctx context.Context, in *DouyinUserRequest, opts ...grpc.CallOption) (*DouyinUserResponse, error) {
	client := pb.NewCoreClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultCore) DouyinUserRegister(ctx context.Context, in *DouyinUserRegisterRequest, opts ...grpc.CallOption) (*DouyinUserRegisterResponse, error) {
	client := pb.NewCoreClient(m.cli.Conn())
	return client.DouyinUserRegister(ctx, in, opts...)
}

func (m *defaultCore) DouyinUserLogin(ctx context.Context, in *DouyinUserLoginRequest, opts ...grpc.CallOption) (*DouyinUserLoginResponse, error) {
	client := pb.NewCoreClient(m.cli.Conn())
	return client.DouyinUserLogin(ctx, in, opts...)
}

func (m *defaultCore) DouyinFeed(ctx context.Context, in *DouyinFeedRequest, opts ...grpc.CallOption) (*DouyinFeedResponse, error) {
	client := pb.NewCoreClient(m.cli.Conn())
	return client.DouyinFeed(ctx, in, opts...)
}

func (m *defaultCore) DouyinPublishAction(ctx context.Context, in *DouyinPublishActionRequest, opts ...grpc.CallOption) (*DouyinPublishActionResponse, error) {
	client := pb.NewCoreClient(m.cli.Conn())
	return client.DouyinPublishAction(ctx, in, opts...)
}

func (m *defaultCore) DouyinPublishList(ctx context.Context, in *DouyinPublishListRequest, opts ...grpc.CallOption) (*DouyinPublishListResponse, error) {
	client := pb.NewCoreClient(m.cli.Conn())
	return client.DouyinPublishList(ctx, in, opts...)
}
