// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id               int64  `json:"id"`               // 用户id
	Name             string `json:"name"`             // 用户名称
	Follow_count     int64  `json:"follow_count"`     // 关注总数
	Follower_count   int64  `json:"follower_count"`   // 粉丝总数
	Is_follow        bool   `json:"is_follow"`        // true-已关注，false-未关注
	Avatar           string `json:"avatar"`           //用户头像
	Background_image string `json:"background_image"` //用户个人页顶部大图
	Signature        string `json:"signature"`        //个人简介
	Total_favorited  int64  `json:"total_favorited"`  //获赞数量
	Work_count       int64  `json:"work_count"`       //作品数量
	Favorite_count   int64  `json:"favorite_count"`   //点赞数量
}

type DouyinUserRegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type DouyinUserRegisterResp struct {
	Status_code int32  `json:"status_code"` // 状态码，0-成功，其他值-失败
	Status_msg  string `json:"status_msg"`  // 返回状态描述
	User_id     int64  `json:"user_id"`     // 用户id
	Token       string `json:"token"`       // 用户鉴权token
}

type DouyinUserLoginReq struct {
	Username string `json:"username"` // 登录用户名
	Password string `json:"password"` // 登录密码
}

type DouyinUserLoginResp struct {
	Status_code int32  `json:"status_code"` // 状态码，0-成功，其他值-失败
	Status_msg  string `json:"status_msg"`  // 返回状态描述
	User_id     int64  `json:"user_id"`     // 用户id
	Token       string `json:"token"`       // 用户鉴权token
}

type DouyinUserReq struct {
	User_id int64  `json:"user_id"` // 用户id
	Token   string `json:"token"`   // 用户鉴权token
}

type DouyinUserResp struct {
	Status_code int32  `json:"status_code"` // 状态码，0-成功，其他值-失败
	Status_msg  string `json:"status_msg"`  // 返回状态描述
	User User `json:"user"`
}

type Video struct {
	Id             int64  `json:"id"`             // 视频唯一标识
	Author User `json:"author"`
	Play_url       string `json:"play_url"`       // 视频播放地址
	Cover_url      string `json:"cover_url"`      // 视频封面地址
	Favorite_count int64  `json:"favorite_count"` // 视频的点赞总数
	Comment_count  int64  `json:"comment_count"`  // 视频的评论总数
	Is_favorite    bool   `json:"is_favorite"`    // true-已点赞，false-未点赞
	Title          string `json:"title"`          // 视频标题
}

type DouyinFeedReq struct {
	Latest_time int64 `json:"latest_time"` // 可选参数，限制返回视频的最新投稿时间戳，精确到秒，不填表示当前时间
	Token       string `json:"token"`       // 可选参数，登录用户设置
}

type DouyinFeedResp struct {
	Status_code int32   `json:"status_code"` // 状态码，0-成功，其他值-失败
	Status_msg  string  `json:"status_msg"`  // 返回状态描述
	Video_list  []Video `json:"video_list"`  // 视频列表
	Next_time   int64   `json:"next_time"`   // 本次返回的视频中，发布最早的时间，作为下次请求时的latest_time
}

type DouyinPublishActionrReq struct {
	Token string `json:"token"` // 用户鉴权token
	Data  []byte `json:"data"`  // 视频数据
	Title string `json:"title"` // 视频标题
}

type DouyinPublishActionResp struct {
	Status_code int32  `json:"status_code"` // 状态码，0-成功，其他值-失败
	Status_msg  string `json:"status_msg"`  // 返回状态描述
}

type DouyinPublishListReq struct {
	User_id int64  `json:"user_id"` // 用户id
	Token   string `json:"token"`   // 用户鉴权token
}

type DouyinPublishListResp struct {
	Status_code int32   `json:"status_code"` // 状态码，0-成功，其他值-失败
	Status_msg  string  `json:"status_msg"`  // 返回状态描述
	Video_list  []Video `json:"video_list"`  // 用户发布的视频列表
}
