// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	douyinComment "douyin/api/douyin/internal/handler/douyinComment"
	douyinFavorite "douyin/api/douyin/internal/handler/douyinFavorite"
	douyinMessage "douyin/api/douyin/internal/handler/douyinMessage"
	douyinRelation "douyin/api/douyin/internal/handler/douyinRelation"
	douyinUser "douyin/api/douyin/internal/handler/douyinUser"
	feed "douyin/api/douyin/internal/handler/feed"
	publish "douyin/api/douyin/internal/handler/publish"
	"douyin/api/douyin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: douyinUser.DouyinUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: douyinUser.DouyinUserRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: douyinUser.DouyinUserLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/action",
				Handler: publish.DouyinPublishActionrHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: publish.DouyinPublishListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/publish"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/douyin/feed",
				Handler: feed.DouyinFeedHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/action",
				Handler: douyinFavorite.DouyinFavoriteActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: douyinFavorite.DouyinFavoriteListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/favorite"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/action",
				Handler: douyinComment.DouyinCommentActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: douyinComment.DouyinCommentListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/comment"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/action",
				Handler: douyinRelation.DouyinRelationActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/follow/list",
				Handler: douyinRelation.DouyinRelationFollowListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/follower/list",
				Handler: douyinRelation.DouyinRelationFollowerListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/friend/list",
				Handler: douyinRelation.DouyinRelationFriendListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/relation"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/chat",
				Handler: douyinMessage.DouyinMessageChatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/action",
				Handler: douyinMessage.DouyinMessageActionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/message"),
	)
}
